# docker-compose.yml
#version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: flibusta-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-flibusta}
      - MYSQL_USER=${DB_USER:-flibusta}
      - MYSQL_PASSWORD=${DB_PASSWORD:-flibusta}
      - TZ=Europe/Moscow
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_unicode_ci
      - --skip-character-set-client-handshake  # ИГНОРИРОВАТЬ клиентские настройки
      - --innodb-buffer-pool-size=128M #(было 128M)
      - --key-buffer-size=32M #(было 8M)
      - --max-connections=100 #(было 151)
      - --query-cache-size=0 #(совпадает)
      - --tmp-table-size=16M #(было 16M)
      - --max-heap-table-size=16M #(было 16M)
      - --table-open-cache=400 #(было 2000)
      - --thread-cache-size=8 #(было 0) - определяется автоматически
      - --innodb-log-file-size=32M #(было 48M)
      - --performance-schema=ON #(было ON)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.8'
    volumes:
      - mariadb_data:/var/lib/mysql  # Тот же volume
      - ./db_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

  bot:
    image: holyshithappens/flbst-bot-mdb
    container_name: flibusta-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=mariadb
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.4'
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
    user: "1000:1000"

volumes:
  mariadb_data: